#!/bin/sh
# Fix up mount points device node names.
#
# /data needs to be mounted in initrd, but there is no udev that early,
# which means there is no /dev/block/platform/*/by-name/* (or bootdevice).
# This file is a map from the "by-name" path to /dev/mmcblkMpN.
# It also serves dhd to convert fstab and *.rc mount entries to systemd units,
# because at that boot stage there is still no udev "by-name" paths, even when
# systemd starts to execut the "*.mount" units.

DEVICE=$1
shift

echo "Fixing mount-points for device $DEVICE"

case "$DEVICE" in
    "karatep")
        sed -i \
            -e 's block/bootdevice/by-name/DDR mmcblk0p31 ' \
            -e 's block/bootdevice/by-name/aboot mmcblk0p11 ' \
            -e 's block/bootdevice/by-name/abootbak mmcblk0p12 ' \
            -e 's block/bootdevice/by-name/apdp mmcblk0p36 ' \
            -e 's block/bootdevice/by-name/boot mmcblk0p34 ' \
            -e 's block/bootdevice/by-name/cache mmcblk0p50 ' \
            -e 's block/bootdevice/by-name/cmnlib mmcblk0p5 ' \
            -e 's block/bootdevice/by-name/cmnlib64 mmcblk0p7 ' \
            -e 's block/bootdevice/by-name/cmnlib64bak mmcblk0p8 ' \
            -e 's block/bootdevice/by-name/cmnlibbak mmcblk0p6 ' \
            -e 's block/bootdevice/by-name/config mmcblk0p42 ' \
            -e 's block/bootdevice/by-name/devcfg mmcblk0p26 ' \
            -e 's block/bootdevice/by-name/devcfgbak mmcblk0p27 ' \
            -e 's block/bootdevice/by-name/devinfo mmcblk0p13 ' \
            -e 's block/bootdevice/by-name/dip mmcblk0p45 ' \
            -e 's block/bootdevice/by-name/dpo mmcblk0p38 ' \
            -e 's block/bootdevice/by-name/dsp mmcblk0p28 ' \
            -e 's block/bootdevice/by-name/fsc mmcblk0p18 ' \
            -e 's block/bootdevice/by-name/fsg mmcblk0p32 ' \
            -e 's block/bootdevice/by-name/keymaster mmcblk0p9 ' \
            -e 's block/bootdevice/by-name/keymasterbak mmcblk0p10 ' \
            -e 's block/bootdevice/by-name/keystore mmcblk0p41 ' \
            -e 's block/bootdevice/by-name/kpadA mmcblk0p17 ' \
            -e 's block/bootdevice/by-name/kpadB mmcblk0p33 ' \
            -e 's block/bootdevice/by-name/limits mmcblk0p14 ' \
            -e 's block/bootdevice/by-name/lksecapp mmcblk0p3 ' \
            -e 's block/bootdevice/by-name/lksecappbak mmcblk0p4 ' \
            -e 's block/bootdevice/by-name/mcfg mmcblk0p48 ' \
            -e 's block/bootdevice/by-name/mdtp mmcblk0p46 ' \
            -e 's block/bootdevice/by-name/misc mmcblk0p40 ' \
            -e 's block/bootdevice/by-name/modem mmcblk0p1 ' \
            -e 's block/bootdevice/by-name/modemst1 mmcblk0p29 ' \
            -e 's block/bootdevice/by-name/modemst2 mmcblk0p30 ' \
            -e 's block/bootdevice/by-name/mota mmcblk0p44 ' \
            -e 's block/bootdevice/by-name/mrd mmcblk0p51 ' \
            -e 's block/bootdevice/by-name/msadp mmcblk0p37 ' \
            -e 's block/bootdevice/by-name/oem mmcblk0p43 ' \
            -e 's block/bootdevice/by-name/persist mmcblk0p49 ' \
            -e 's block/bootdevice/by-name/preload mmcblk0p53 ' \
            -e 's block/bootdevice/by-name/prov32 mmcblk0p15 ' \
            -e 's block/bootdevice/by-name/prov32bak mmcblk0p16 ' \
            -e 's block/bootdevice/by-name/recovery mmcblk0p35 ' \
            -e 's block/bootdevice/by-name/rpm mmcblk0p22 ' \
            -e 's block/bootdevice/by-name/rpmbak mmcblk0p23 ' \
            -e 's block/bootdevice/by-name/sbl1 mmcblk0p20 ' \
            -e 's block/bootdevice/by-name/sbl1bak mmcblk0p21 ' \
            -e 's block/bootdevice/by-name/sec mmcblk0p2 ' \
            -e 's block/bootdevice/by-name/splash mmcblk0p39 ' \
            -e 's block/bootdevice/by-name/ssd mmcblk0p19 ' \
            -e 's block/bootdevice/by-name/syscfg mmcblk0p47 ' \
            -e 's block/bootdevice/by-name/system mmcblk0p52 ' \
            -e 's block/bootdevice/by-name/tz mmcblk0p24 ' \
            -e 's block/bootdevice/by-name/tzbak mmcblk0p25 ' \
            -e 's block/bootdevice/by-name/userdata mmcblk0p54 ' \
            "$@"
        ;;
    *)
        cat <<EOF

****************************************************************
****************************************************************
ERROR: $DEVICE does not have mountpoint fixup data - see
       Sailfish OS HADK for details on how to fix this.
****************************************************************
****************************************************************

EOF
        exit 1
        ;;
esac

